name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install -y build-essential

    - name: Configure project
      run: ./configure

    - name: Build project
      run: make

    - name: Run tests
      run: make check

    - name: Run distribution checks
      run: make distcheck
